<a href="https://colab.research.google.com/github/mrubiob/python/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x=np.array([1,5,3,8])
print(x)
x+1 #si se le quiere sumar a cada elemento + 1

[1 5 3 8]


array([2, 6, 4, 9])

In [ ]:
x_list = [1,3,5,8]
print(x_list)

[1, 3, 5, 8]


In [ ]:
#crear arreglo numpy de sólo números 1
array_ceros=np.zeros(5)
print(array_ceros)

[0. 0. 0. 0. 0.]


In [ ]:
#crear arreglo numpy con solo elementos 1
arrays_uno=np.ones(6)
print(arrays_uno)

[1. 1. 1. 1. 1. 1.]


In [ ]:
#range en numpy, nos permite generar rangos de numeros
array_rango = np.arange(10)
print(array_rango)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#rango numpy entre 1 y 10, pero con incremento 0.5
array_medio = np.arange(1,10,0.5)
print(array_medio)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
